name: smart_shop
description: A mini e-commerce app using Flutter

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.1

  # HTTP client for REST API
  http: ^1.2.1

  # Local Storage
  shared_preferences: ^2.2.2

  # Routing
  go_router: ^16.0.0

  # Icons
  flutter_svg: ^2.0.9
  font_awesome_flutter: ^10.7.0

  # UI/UX
  flutter_rating_bar: ^4.0.1
  shimmer: ^3.0.0
  pull_to_refresh: ^2.0.0

  # For image caching (optional)
  cached_network_image: ^3.3.1

  # Animations (optional for smooth transitions)
  animated_splash_screen: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/app_logo.png
    - assets/login_bg.png
